apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-project1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: app-engine
          image: azure2233.azurecr.io/flaskapi1:12.0.4
          resources:
            requests:
              cpu: 100m
          imagePullPolicy: Always
          ports:
          - containerPort: 5000