apiVersion: v1
kind: Service
metadata:
  name: py-project-service
spec:
  selector:
    app: app1
  ports:
  - protocol: TCP
    port: 5000  # adjust as needed
    targetPort: 5000  # adjust based on your Flask app port
  type: LoadBalancer